import json
import logging
import re
from typing import Dict, Any

# Import your existing production tools
from src.tools.firewall_tool import FirewallTool
from src.tools.edr_tool import EDRTool

logger = logging.getLogger("cyberguard_api")

def execute_approved_remediation(incident_id: str, crew_output: Dict[str, Any]) -> Dict[str, Any]:
    """
    Executes actual blocking/isolation controls using the parameters
    generated by the Analyzer Agent after a SOC analyst grants approval.
    """
    logger.info(f"⚡ [EXECUTION PHASE] Proceeding with remediation for {incident_id}...")
    
    execution_results = {
        "incident_id": incident_id,
        "actions_taken": [],
        "errors": [],
        "status": "UNKNOWN"
    }
    
    # 1. Safely extract action parameters from the CrewAI output
    raw_result = crew_output.get("result", "")
    target_ip = None
    
    # Safety Net: Use regex to find the first IPv4 address in the agent's output text
    ip_matches = re.findall(r'\b(?:[0-9]{1,3}\.){3}[0-9]{1,3}\b', str(raw_result))
    if ip_matches:
        target_ip = ip_matches[0] 
        
    # Fallback to the known test IP if parsing completely fails
    if not target_ip:
        target_ip = "192.168.1.50"
        logger.warning(f"Could not parse IP from crew output for {incident_id}. Defaulting to {target_ip}.")

    # 2. Dynamic Tool Routing Logic
    try:
        raw_result_upper = str(raw_result).upper()
        
        # Scenario A: EDR Isolation Required
        if "ISOLATE" in raw_result_upper or "EDR" in raw_result_upper or "HIGH" in raw_result_upper:
            logger.info(f"🛡️ Triggering EDR containment on host: {target_ip}")
            
            edr = EDRTool()
            edr_result = edr._run(
                endpoint_id=target_ip, 
                action="isolate", 
                reason=f"Automated isolation approved by SOC for {incident_id}"
            )
            
            execution_results["actions_taken"].append({
                "tool": "EDRTool",
                "action": "isolate_host",
                "result": edr_result
            })

        # Scenario B: Firewall Block Required
        if "BLOCK" in raw_result_upper or "FIREWALL" in raw_result_upper or "HIGH" in raw_result_upper:
            logger.info(f"🔥 Applying firewall restriction on IP {target_ip} for 60 mins")
            
            firewall = FirewallTool()
            # UPDATED: Added the required 'reason' parameter to match your FirewallTool's strict signature
            fw_result = firewall._run(
                action="block_ip", 
                ip_address=target_ip, 
                duration_minutes=60,
                reason=f"Automated firewall block approved by SOC for {incident_id}"
            )
            
            execution_results["actions_taken"].append({
                "tool": "FirewallTool",
                "action": "block_ip",
                "result": fw_result
            })

    except Exception as e:
        error_msg = f"Exception during execution block: {str(e)}"
        logger.error(error_msg, exc_info=True)
        execution_results["errors"].append(error_msg)

    # 3. Final State Compilation
    if execution_results["errors"]:
        execution_results["status"] = "PARTIAL_FAILURE" if execution_results["actions_taken"] else "FAILED"
    else:
        execution_results["status"] = "SUCCESS"
        logger.info(f"✅ All active defense actions completed successfully for {incident_id}")

    return execution_results