name: Deploy to Google Cloud Run

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: 'projects/93337753347/locations/global/workloadIdentityPools/github-pool/providers/github-provider'
          service_account: 'github-actions-deployer@my-agentic-lab.iam.gserviceaccount.com'

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure Docker
        run: gcloud auth configure-docker asia-south1-docker.pkg.dev

      - name: Build and Push to Artifact Registry
        run: |
          docker build -t asia-south1-docker.pkg.dev/my-agentic-lab/cyberguard-repo/cyberguard-api:latest .
          docker push asia-south1-docker.pkg.dev/my-agentic-lab/cyberguard-repo/cyberguard-api:latest

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy cyberguard-ai \
            --image asia-south1-docker.pkg.dev/my-agentic-lab/cyberguard-repo/cyberguard-api:latest \
            --platform managed \
            --region asia-south1 \
            --allow-unauthenticated

          gcloud run services update cyberguard-ai \
            --cpu-boost \
            --no-cpu-throttling \
            --region asia-south1